### ISSUE TITLE
Supporting additional build options

### ISSUE THREAD

**Issue by nir0s** [cloudify-cosmo/depypi#3]
Currently, we hardcode `sdist` when running depypi to upload a package. What about `bdist`? What about `bdist_wheel`? I suggest we add a feature to pass additional flags to the `python setup.py` command but more specifically, add a specific flag called `--dist-type` or something of that sort which would receive a distribution type (https://docs.python.org/2/distutils/builtdist.html).

**Comment by gilzellner** [comment]
done.
